# Generated by Django 4.2.16 on 2026-06-14 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='邀请码')),
                ('role', models.CharField(choices=[('inspector', '巡检员'), ('admin', '管理员')], max_length=20, verbose_name='角色')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_codes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_code', to=settings.AUTH_USER_MODEL, verbose_name='使用人')),
            ],
            options={
                'verbose_name': '邀请码',
                'verbose_name_plural': '邀请码',
                'db_table': 'gt_invitation_code',
                'ordering': ['-created_at'],
            },
        ),
    ]
