# Generated by Django 4.2.16 on 2026-06-14 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='成就编码')),
                ('name', models.CharField(max_length=50, verbose_name='成就名称')),
                ('description', models.CharField(max_length=255, verbose_name='成就描述')),
                ('icon', models.CharField(blank=True, default='', max_length=255, verbose_name='成就图标')),
                ('category', models.CharField(choices=[('delivery', '投放达人'), ('points', '积分王者'), ('streak', '连续挑战'), ('special', '特殊成就')], max_length=20, verbose_name='分类')),
                ('points_reward', models.IntegerField(default=0, verbose_name='奖励积分')),
                ('condition_type', models.CharField(max_length=50, verbose_name='条件类型')),
                ('condition_value', models.IntegerField(default=0, verbose_name='条件值')),
                ('rarity', models.SmallIntegerField(default=1, verbose_name='稀有度 1-5')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '绿色成就',
                'verbose_name_plural': '绿色成就',
                'db_table': 'gt_achievement',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('recyclable', '可回收物'), ('kitchen', '厨余垃圾'), ('hazardous', '有害垃圾'), ('other', '其他垃圾')], max_length=20, verbose_name='垃圾分类')),
                ('weight', models.FloatField(verbose_name='重量(kg)')),
                ('points_earned', models.IntegerField(default=0, verbose_name='获得积分')),
                ('points_per_kg', models.FloatField(default=0, verbose_name='每公斤积分')),
                ('status', models.SmallIntegerField(choices=[(0, '待审核'), (1, '已完成'), (2, '异常'), (3, '已驳回')], default=1, verbose_name='状态')),
                ('image', models.CharField(blank=True, default='', max_length=255, verbose_name='投放照片')),
                ('inspector_id', models.BigIntegerField(blank=True, null=True, verbose_name='巡检员ID')),
                ('inspection_remark', models.CharField(blank=True, default='', max_length=255, verbose_name='巡检备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投放时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '投放记录',
                'verbose_name_plural': '投放记录',
                'db_table': 'gt_delivery_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(max_length=50, unique=True, verbose_name='商品编号')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='商品描述')),
                ('image', models.CharField(blank=True, default='', max_length=255, verbose_name='商品图片')),
                ('points_price', models.IntegerField(verbose_name='积分价格')),
                ('market_price', models.FloatField(default=0, verbose_name='市场价格')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sold', models.IntegerField(default=0, verbose_name='已售数量')),
                ('status', models.SmallIntegerField(choices=[(0, '下架'), (1, '上架')], default=1, verbose_name='状态')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='商品分类')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '兑换商品',
                'verbose_name_plural': '兑换商品',
                'db_table': 'gt_exchange_goods',
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('goods_name', models.CharField(max_length=100, verbose_name='商品名称快照')),
                ('goods_image', models.CharField(blank=True, default='', max_length=255, verbose_name='商品图片快照')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('total_points', models.IntegerField(verbose_name='消耗总积分')),
                ('status', models.SmallIntegerField(choices=[(0, '待发货'), (1, '已发货'), (2, '已完成'), (3, '已取消'), (4, '待领取')], default=0, verbose_name='状态')),
                ('receiver_name', models.CharField(blank=True, default='', max_length=50, verbose_name='收货人')),
                ('receiver_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='收货电话')),
                ('receiver_address', models.CharField(blank=True, default='', max_length=255, verbose_name='收货地址')),
                ('logistics_no', models.CharField(blank=True, default='', max_length=50, verbose_name='物流单号')),
                ('logistics_company', models.CharField(blank=True, default='', max_length=50, verbose_name='物流公司')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '兑换订单',
                'verbose_name_plural': '兑换订单',
                'db_table': 'gt_exchange_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('wrong_category', '分类错误'), ('bin_full', '投放点满溢'), ('bin_damage', '设备损坏'), ('hygiene', '卫生问题'), ('other', '其他')], max_length=30, verbose_name='异常类型')),
                ('description', models.TextField(verbose_name='异常描述')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='照片列表')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='位置')),
                ('status', models.SmallIntegerField(choices=[(0, '待处理'), (1, '处理中'), (2, '已处理'), (3, '已驳回')], default=0, verbose_name='状态')),
                ('handle_remark', models.TextField(blank=True, default='', verbose_name='处理备注')),
                ('points_reward', models.IntegerField(default=0, verbose_name='奖励积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
            ],
            options={
                'verbose_name': '巡检异常上报',
                'verbose_name_plural': '巡检异常上报',
                'db_table': 'gt_inspection_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.IntegerField(default=0, verbose_name='累计获得')),
                ('total_spent', models.IntegerField(default=0, verbose_name='累计消费')),
                ('total_expired', models.IntegerField(default=0, verbose_name='累计过期')),
                ('balance', models.IntegerField(default=0, verbose_name='当前余额')),
                ('frozen', models.IntegerField(default=0, verbose_name='冻结积分')),
                ('level', models.SmallIntegerField(default=1, verbose_name='用户等级')),
                ('level_name', models.CharField(default='环保新手', max_length=20, verbose_name='等级名称')),
                ('next_level_points', models.IntegerField(default=1000, verbose_name='下一等级所需积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '积分账户',
                'verbose_name_plural': '积分账户',
                'db_table': 'gt_point_account',
            },
        ),
        migrations.CreateModel(
            name='PointRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('earn', '获得'), ('spend', '消费'), ('expire', '过期'), ('adjust', '调整')], max_length=20, verbose_name='类型')),
                ('source', models.CharField(choices=[('delivery', '投放垃圾'), ('exchange', '积分兑换'), ('achievement', '成就奖励'), ('activity', '活动奖励'), ('system', '系统调整'), ('manual', '人工调整')], max_length=20, verbose_name='来源')),
                ('points', models.IntegerField(verbose_name='积分数值(正数增加,负数减少)')),
                ('balance_before', models.IntegerField(verbose_name='变动前余额')),
                ('balance_after', models.IntegerField(verbose_name='变动后余额')),
                ('related_id', models.CharField(blank=True, default='', max_length=50, verbose_name='关联业务ID')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水',
                'db_table': 'gt_point_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_code', models.CharField(max_length=50, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('location', models.CharField(max_length=255, verbose_name='安装位置')),
                ('community', models.CharField(blank=True, default='', max_length=100, verbose_name='所属社区')),
                ('status', models.SmallIntegerField(choices=[(0, '离线'), (1, '在线'), (2, '维护中'), (3, '故障')], default=1, verbose_name='状态')),
                ('capacity', models.FloatField(default=100.0, verbose_name='总容量(L)')),
                ('used', models.FloatField(default=0.0, verbose_name='已使用(L)')),
                ('last_online', models.DateTimeField(blank=True, null=True, verbose_name='最后在线时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '智能投放点',
                'verbose_name_plural': '智能投放点',
                'db_table': 'gt_smart_bin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='解锁时间')),
                ('is_new', models.BooleanField(default=True, verbose_name='是否新解锁')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='points.achievement', verbose_name='成就')),
            ],
            options={
                'verbose_name': '用户成就',
                'verbose_name_plural': '用户成就',
                'db_table': 'gt_user_achievement',
                'ordering': ['-unlocked_at'],
            },
        ),
    ]
