# Generated by Django 4.2.16 on 2026-06-14 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='pointrecord',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='points.pointaccount', verbose_name='积分账户'),
        ),
        migrations.AddField(
            model_name='pointrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_records', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='pointaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_account', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='points.smartbin', verbose_name='关联投放点'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_inspections', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='point_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='points.pointrecord', verbose_name='积分流水'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_inspections', to=settings.AUTH_USER_MODEL, verbose_name='上报人'),
        ),
        migrations.AddField(
            model_name='exchangeorder',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='points.exchangegoods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='exchangeorder',
            name='point_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='points.pointrecord', verbose_name='积分流水'),
        ),
        migrations.AddField(
            model_name='exchangeorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='points.smartbin', verbose_name='投放点'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='point_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='points.pointrecord', verbose_name='积分流水'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
