# Generated by Django 4.2.16 on 2026-06-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangegoods',
            name='type',
            field=models.CharField(choices=[('physical', '实物商品'), ('virtual', '虚拟券')], default='physical', max_length=20, verbose_name='商品类型'),
        ),
        migrations.AddField(
            model_name='exchangeorder',
            name='goods_type',
            field=models.CharField(default='physical', max_length=20, verbose_name='商品类型快照'),
        ),
        migrations.AddField(
            model_name='exchangeorder',
            name='voucher_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='虚拟券兑换码'),
        ),
    ]
