# Generated by Django 4.2.16 on 2026-06-14 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenPassCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='通行码ID')),
                ('encrypted_data', models.TextField(verbose_name='加密数据')),
                ('signature', models.CharField(max_length=256, verbose_name='签名')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('status', models.SmallIntegerField(choices=[(0, '未使用'), (1, '已使用'), (2, '已过期'), (3, '已作废')], default=0, verbose_name='状态')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('bin_code', models.CharField(blank=True, default='', max_length=50, verbose_name='关联投放点编号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_codes', to=settings.AUTH_USER_MODEL, verbose_name='验证人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_codes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '绿色通行码',
                'verbose_name_plural': '绿色通行码',
                'db_table': 'gt_green_pass_code',
                'ordering': ['-created_at'],
            },
        ),
    ]
