# Generated by Django 4.2.16 on 2026-06-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_greenpasscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbin',
            name='category',
            field=models.CharField(choices=[('recyclable', '可回收物'), ('kitchen', '厨余垃圾'), ('hazardous', '有害垃圾'), ('other', '其他垃圾'), ('mixed', '混合投放')], default='mixed', max_length=20, verbose_name='垃圾类型'),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='capacity',
            field=models.FloatField(default=100.0, verbose_name='容量上限(L)'),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='location',
            field=models.CharField(max_length=255, verbose_name='安装地址'),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='name',
            field=models.CharField(max_length=100, verbose_name='站点名称'),
        ),
    ]
