# Generated by Django 4.2.16 on 2026-06-14 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_seed_goods_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_reports', to='points.deliveryrecord', verbose_name='关联投递记录'),
        ),
    ]
