# Generated by Django 4.2.16 on 2026-06-15 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0005_inspectionreport_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('delivery_approved', '投递审核通过'), ('delivery_rejected', '投递审核驳回'), ('exchange_success', '兑换成功'), ('exchange_shipped', '兑换已发货'), ('exchange_completed', '兑换已完成'), ('exchange_cancelled', '兑换已取消'), ('inspection_resolved', '巡检已处理'), ('inspection_rejected', '巡检已驳回')], max_length=30, verbose_name='通知类型')),
                ('title', models.CharField(max_length=100, verbose_name='通知标题')),
                ('content', models.CharField(max_length=500, verbose_name='通知内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('related_id', models.CharField(blank=True, default='', max_length=50, verbose_name='关联业务ID')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '消息通知',
                'verbose_name_plural': '消息通知',
                'db_table': 'gt_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
